### ISSUE TITLE
issue with deploy

### ISSUE THREAD

**Issue by BLVCK-ANGEL** [Ashanime/Ashanime-Web-App#21]
it deployed but there is a issue when i click login or login anonymously it never loader nxt page it strucks that page.
when register it show like that 

Registration failed
Firebase: Error (auth/operation-not-allowed).

**Comment by K3NOXOFFICIAL** [comment]
@BLVCK-ANGEL 
It seems like you didn't go through our [Installation Manual,](https://github.com/Ashanime/Ashanime-Web-App/wiki/Installation) you need to do The Firebase setup before you can use the Webapp.
Please refer to Firebase installation and Configuration.



If you need further help with your issue, you can join our Discord server. There, you can connect with other users and get additional support and assistance. To join the server, you will need to install the Discord app and use the [invite link](https://discord.gg/vDkbHKsRZM) to join the server.
