### ISSUE TITLE
[Readme Update] Update Documentation to Explain the Backend Setup

### ISSUE THREAD

**Issue by AhmarZaidi** [Ashanime/Ashanime-Web-App#27]
While setting up this project locally I found that the backend [consumet](https://github.com/consumet/api.consumet.org) setup has not been explained.

Should I make a PR to update the Readme.md explaining how to set that up?

**Comment by ahmedalashhab** [comment]
Please feel free to do so! That would be awesome.

**Comment by Eternal-TMI** [comment]
there is no a to Z listed anime 
can you work it?

**Comment by ahmedalashhab** [comment]
There is. In the genres page, search through 'Alphabetical'
