### ISSUE TITLE
The website isn't working 

### ISSUE THREAD

**Issue by anime-kun32** [Ashanime/Ashanime-Web-App#30]
I just deployed the website on vercel and I wanted to try it out but the entire website page was empty  
![Screenshot_20240715-064758](https://github.com/user-attachments/assets/d891a18e-73cd-4bf1-82a6-087897b3724e)
![Screenshot_20240715-065212](https://github.com/user-attachments/assets/68d28e41-75fc-4945-9c78-8006b5da762d)
What's going on

**Comment by ahmedalashhab** [comment]
@anime-kun32 Hi! You will need to implement a proxy and host your own consumet API on vercel.
