### ISSUE TITLE
DB Examples

### ISSUE THREAD

**Issue by 002-sans** [Ashanime/Ashanime-Web-App#4]
How must be the DB ?

Like:

- Naruto
  - embed
    - 0: https://link.com

**Comment by ahmedalashhab** [comment]
Hi,

I'm sorry, I don't understand your question. May you please clarify?

**Comment by 002-sans** [comment]
my firebase look like that;
```json
{
  "A Silent Voice VF": {
    "embed": [
      "https://video.sibnet.ru/shell.php?videoid=4824807&share=1"
    ]
  }
}
```

what's the correct format ?

**Comment by ahmedalashhab** [comment]
On my firebase realtime database, the data is outlayed as follows: 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/96653465/194706629-3ff5a629-53e5-4073-998b-39bbd39649ce.png">.

That's how i've coded the app to store information and consequently read it.. Perhaps you changed the firebase writing and reading code?

In addition, did you change the API being used?

If possible,  please do inform me what you changed in terms of code and do send me some screenshots so I may better assist you.

I'll be releasing a new update soon that should fix many bugs as well.

**Comment by 002-sans** [comment]
I didn't change your code, when I run the program, I only see this:
![image](https://user-images.githubusercontent.com/99873347/194708215-4e35ab83-9209-4573-a749-54933067c714.png)
I said to myself that it's a problem with the database

**Comment by ahmedalashhab** [comment]
Oh I see. I think I know what is wrong. There has been a very recent API domain change. I'll update my code today to make sure everything goes back to working condition. Thank you for informing me about this.

**Comment by 002-sans** [comment]
ok, thanks !!!

**Comment by ahmedalashhab** [comment]
Just released the new update. Check it out and tell me what you think :)

**Comment by ahmedalashhab** [comment]
Another point is that currently there are backend issues causing the app not to work well. It should be fixed by tomorrow.
