### ISSUE TITLE
Feature Request: MyAnimeList Tracker

### ISSUE THREAD

**Issue by ghost** [Ashanime/Ashanime-Web-App#5]
Hello Team Ashanime, It would be great if there was a feature where it the MyAnimeList account syncs to Ashanime. That way it automatically watchlists all the animes I wanted to watch with a single click of a button.

**Comment by ahmedalashhab** [comment]
I can definitely look into this functionality once I have enough time.

**Comment by ghost** [comment]
Thanks for the response @ahmedalashhab, 

Looking forward to this feature. Might as well participate on your project if time is by my side!

**Comment by ahmedalashhab** [comment]
@ricemashi You're more than welcome to do so :) 
Currently I'm looking into the implementation of various hard coded subtitle languages as well as doing general maintenance and bug fixes.
