### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [Ashanime/Ashanime-Web-App#6]
When I try to build the website with vercel it keeps saying 

Failed to compile.

Module not found: Error: Can't resolve './firebaseConfig' in '/vercel/path0/src/firebase'

Error: Command "npm run build" exited with 1

Is there something I can do?

**Comment by ahmedalashhab** [comment]
Please see me response to issue #7 .

**Comment by K3NOXOFFICIAL** [comment]
Fixed the issue by deleting

import { firebaseConfig } from "./firebaseConfig";

and adding

export const firebaseConfig = {
	apiKey: "sjhHDJsh82hJHdh3jHJDHJQk4398",
	authDomain: "yourdomain.firebaseapp.com",
	databaseURL: "https://jgjfhg453EHQHT.asia-east1.firebasedatabase.app",
	projectId: "your project id",
	storageBucket: "projectid.appspot.com",
	messagingSenderId: "333747474747477",
	appId: "yourappid",
	measurementId: "R-FKJHSJW",
};

in ./src/firebase/firebase.js

**Comment by ahmedalashhab** [comment]
Awesome! Glad to hear it worked out for you. This means bookmarks, continue watching, and the whole app is working well now right? In terms of providers, I'd advise turning off Animefox and Crunchyroll right now as the API is facing difficulties. Only Gogo seems to be working well for the time being.

**Comment by K3NOXOFFICIAL** [comment]
Yea I'll archieve this problem since its solved.
Thanks
